<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Autos extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Autos_model');
    } 

    /*
     * Listing of autos
     */
    function index()
    {
        $data['autos'] = $this->Autos_model->get_all_autos();
        
        $data['_view'] = 'autos/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new autos
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status_auto_id' => $this->input->post('status_auto_id'),
				'chauffeur_id' => $this->input->post('chauffeur_id'),
				'nummerplaat' => $this->input->post('nummerplaat'),
				'km_stand' => $this->input->post('km_stand'),
				'onderhoud' => $this->input->post('onderhoud'),
				'keuring' => $this->input->post('keuring'),
				'merk' => $this->input->post('merk'),
				'type' => $this->input->post('type'),
				'a_opmerking' => $this->input->post('a_opmerking'),
            );
            
            $autos_id = $this->Autos_model->add_autos($params);
            redirect('autos/index');
        }
        else
        {
			$this->load->model('Status_auto_model');
			$data['all_status_auto'] = $this->Status_auto_model->get_all_status_auto();

			$this->load->model('Chauffeurs_model');
			$data['all_chauffeurs'] = $this->Chauffeurs_model->get_all_chauffeurs();
            
            $data['_view'] = 'autos/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a autos
     */
    function edit($auto_id)
    {   
        // check if the autos exists before trying to edit it
        $data['autos'] = $this->Autos_model->get_autos($auto_id);
        
        if(isset($data['autos']['auto_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status_auto_id' => $this->input->post('status_auto_id'),
					'chauffeur_id' => $this->input->post('chauffeur_id'),
					'nummerplaat' => $this->input->post('nummerplaat'),
					'km_stand' => $this->input->post('km_stand'),
					'onderhoud' => $this->input->post('onderhoud'),
					'keuring' => $this->input->post('keuring'),
					'merk' => $this->input->post('merk'),
					'type' => $this->input->post('type'),
					'a_opmerking' => $this->input->post('a_opmerking'),
                );

                $this->Autos_model->update_autos($auto_id,$params);            
                redirect('autos/index');
            }
            else
            {
				$this->load->model('Status_auto_model');
				$data['all_status_auto'] = $this->Status_auto_model->get_all_status_auto();

				$this->load->model('Chauffeurs_model');
				$data['all_chauffeurs'] = $this->Chauffeurs_model->get_all_chauffeurs();

                $data['_view'] = 'autos/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The autos you are trying to edit does not exist.');
    } 

    /*
     * Deleting autos
     */
    function remove($auto_id)
    {
        $autos = $this->Autos_model->get_autos($auto_id);

        // check if the autos exists before trying to delete it
        if(isset($autos['auto_id']))
        {
            $this->Autos_model->delete_autos($auto_id);
            redirect('autos/index');
        }
        else
            show_error('The autos you are trying to delete does not exist.');
    }
    
}
