<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chauffeurs extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Chauffeurs_model');
    } 

    /*
     * Listing of chauffeurs
     */
    function index()
    {
        $data['chauffeurs'] = $this->Chauffeurs_model->get_all_chauffeurs();
        
        $data['_view'] = 'chauffeurs/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new chauffeurs
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status_chauffeur_id' => $this->input->post('status_chauffeur_id'),
				'achternaam' => $this->input->post('achternaam'),
				'voornaam' => $this->input->post('voornaam'),
				'straat' => $this->input->post('straat'),
				'postcode' => $this->input->post('postcode'),
				'plaats' => $this->input->post('plaats'),
				'telefoon' => $this->input->post('telefoon'),
				'email' => $this->input->post('email'),
				'c_opmerking' => $this->input->post('c_opmerking'),
            );
            
            $chauffeurs_id = $this->Chauffeurs_model->add_chauffeurs($params);
            redirect('chauffeurs/index');
        }
        else
        {
			$this->load->model('Status_chauffeur_model');
			$data['all_status_chauffeur'] = $this->Status_chauffeur_model->get_all_status_chauffeur();
            
            $data['_view'] = 'chauffeurs/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a chauffeurs
     */
    function edit($chauffeur_id)
    {   
        // check if the chauffeurs exists before trying to edit it
        $data['chauffeurs'] = $this->Chauffeurs_model->get_chauffeurs($chauffeur_id);
        
        if(isset($data['chauffeurs']['chauffeur_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status_chauffeur_id' => $this->input->post('status_chauffeur_id'),
					'achternaam' => $this->input->post('achternaam'),
					'voornaam' => $this->input->post('voornaam'),
					'straat' => $this->input->post('straat'),
					'postcode' => $this->input->post('postcode'),
					'plaats' => $this->input->post('plaats'),
					'telefoon' => $this->input->post('telefoon'),
					'email' => $this->input->post('email'),
					'c_opmerking' => $this->input->post('c_opmerking'),
                );

                $this->Chauffeurs_model->update_chauffeurs($chauffeur_id,$params);            
                redirect('chauffeurs/index');
            }
            else
            {
				$this->load->model('Status_chauffeur_model');
				$data['all_status_chauffeur'] = $this->Status_chauffeur_model->get_all_status_chauffeur();

                $data['_view'] = 'chauffeurs/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The chauffeurs you are trying to edit does not exist.');
    } 

    /*
     * Deleting chauffeurs
     */
    function remove($chauffeur_id)
    {
        $chauffeurs = $this->Chauffeurs_model->get_chauffeurs($chauffeur_id);

        // check if the chauffeurs exists before trying to delete it
        if(isset($chauffeurs['chauffeur_id']))
        {
            $this->Chauffeurs_model->delete_chauffeurs($chauffeur_id);
            redirect('chauffeurs/index');
        }
        else
            show_error('The chauffeurs you are trying to delete does not exist.');
    }
    
}
