<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Autos_model');
        
    }

    function index()
    {
        // Alle autos die binnenkort op onderhoud moeten

        $data['onderhoud'] = $this->Autos_model->get_all_autos_onderhoud();

        $data['keuring'] = $this->Autos_model->get_all_autos_keuring();

        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
