<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Instellingen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Instellingen_model');
    } 

    /*
     * Listing of instellingen
     */
    function index()
    {
        $data['instellingen'] = $this->Instellingen_model->get_all_instellingen();
        
        $data['_view'] = 'instellingen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new instellingen
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'start_tarief' => $this->input->post('start_tarief'),
				'prijs_per_km' => $this->input->post('prijs_per_km'),
				'email' => $this->input->post('email'),
            );
            
            $instellingen_id = $this->Instellingen_model->add_instellingen($params);
            redirect('instellingen/index');
        }
        else
        {            
            $data['_view'] = 'instellingen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a instellingen
     */
    function edit($instellingen_id)
    {   
        // check if the instellingen exists before trying to edit it
        $data['instellingen'] = $this->Instellingen_model->get_instellingen($instellingen_id);
        
        if(isset($data['instellingen']['instellingen_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'start_tarief' => $this->input->post('start_tarief'),
					'prijs_per_km' => $this->input->post('prijs_per_km'),
					'email' => $this->input->post('email'),
                );

                $this->Instellingen_model->update_instellingen($instellingen_id,$params);            
                redirect('instellingen/index');
            }
            else
            {
                $data['_view'] = 'instellingen/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The instellingen you are trying to edit does not exist.');
    } 

    /*
     * Deleting instellingen
     */
    function remove($instellingen_id)
    {
        $instellingen = $this->Instellingen_model->get_instellingen($instellingen_id);

        // check if the instellingen exists before trying to delete it
        if(isset($instellingen['instellingen_id']))
        {
            $this->Instellingen_model->delete_instellingen($instellingen_id);
            redirect('instellingen/index');
        }
        else
            show_error('The instellingen you are trying to delete does not exist.');
    }
    
}
