<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Klanten extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Klanten_model');
    } 

    /*
     * Listing of klanten
     */
    function index()
    {
        $data['klanten'] = $this->Klanten_model->get_all_klanten();
        
        $data['_view'] = 'klanten/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new klanten
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'achternaam' => $this->input->post('achternaam'),
				'voornaam' => $this->input->post('voornaam'),
				'straat' => $this->input->post('straat'),
				'postcode' => $this->input->post('postcode'),
				'plaats' => $this->input->post('plaats'),
				'telefoon' => $this->input->post('telefoon'),
				'email' => $this->input->post('email'),
				'k_opmerking' => $this->input->post('k_opmerking'),
            );
            
            $klanten_id = $this->Klanten_model->add_klanten($params);
            redirect('klanten/index');
        }
        else
        {            
            $data['_view'] = 'klanten/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a klanten
     */
    function edit($klant_id)
    {   
        // check if the klanten exists before trying to edit it
        $data['klanten'] = $this->Klanten_model->get_klanten($klant_id);
        
        if(isset($data['klanten']['klant_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'achternaam' => $this->input->post('achternaam'),
					'voornaam' => $this->input->post('voornaam'),
					'straat' => $this->input->post('straat'),
					'postcode' => $this->input->post('postcode'),
					'plaats' => $this->input->post('plaats'),
					'telefoon' => $this->input->post('telefoon'),
					'email' => $this->input->post('email'),
					'k_opmerking' => $this->input->post('k_opmerking'),
                );

                $this->Klanten_model->update_klanten($klant_id,$params);            
                redirect('klanten/index');
            }
            else
            {
                $data['_view'] = 'klanten/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The klanten you are trying to edit does not exist.');
    } 

    /*
     * Deleting klanten
     */
    function remove($klant_id)
    {
        $klanten = $this->Klanten_model->get_klanten($klant_id);

        // check if the klanten exists before trying to delete it
        if(isset($klanten['klant_id']))
        {
            $this->Klanten_model->delete_klanten($klant_id);
            redirect('klanten/index');
        }
        else
            show_error('The klanten you are trying to delete does not exist.');
    }
    
}
