<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ritten extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ritten_model');
        $this->load->model('Autos_model');
        $this->load->model('Klanten_model');
    } 

    /*
     * Listing of ritten
     */
    function index($offset = 0)
    {
        // Pagination config
        $this->load->library('pagination');

        $config['base_url'] = base_url().'ritten/index/';
        $config['total_rows'] = $this->db->count_all('ritten');;
        $config['per_page'] = 10;
        
        // Pagination init
        $this->pagination->initialize($config);

        $data['ritten'] = $this->Ritten_model->get_all_ritten($config['per_page'], $offset);
        
        $data['_view'] = 'ritten/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ritten
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'klant_id' => $this->input->post('klant_id'),
				'auto_id' => $this->input->post('auto_id'),
				'beginlocatie' => $this->input->post('beginlocatie'),
				'eindlocatie' => $this->input->post('eindlocatie'),
				'afstand' => $this->input->post('afstand'),
				'prijs' => $this->input->post('prijs'),
				'datum' => $this->input->post('datum'),
				'vertrektijd' => $this->input->post('vertrektijd'),
				'aankomsttijd' => $this->input->post('aankomsttijd')
            );
            
            $ritten_id = $this->Ritten_model->add_ritten($params);
            redirect('ritten/index');
        }
        else
        {
			$this->load->model('Klanten_model');
			$data['all_klanten'] = $this->Klanten_model->get_all_klanten();

			$this->load->model('Autos_model');
			$data['all_autos'] = $this->Autos_model->get_all_autos();

            $data['instellingen'] = $this->Ritten_model->get_tarieven();

            $data['_view'] = 'ritten/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ritten
     */
    function edit($ritten_id)
    {   
        // check if the ritten exists before trying to edit it
        $data['ritten'] = $this->Ritten_model->get_ritten($ritten_id);
        
        if(isset($data['ritten']['ritten_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'klant_id' => $this->input->post('klant_id'),
					'auto_id' => $this->input->post('auto_id'),
					'beginlocatie' => $this->input->post('beginlocatie'),
					'eindlocatie' => $this->input->post('eindlocatie'),
					'afstand' => $this->input->post('afstand'),
					'prijs' => $this->input->post('prijs'),
					'datum' => $this->input->post('datum'),
					'vertrektijd' => $this->input->post('vertrektijd'),
					'aankomsttijd' => $this->input->post('aankomsttijd')
                );

                $this->Ritten_model->update_ritten($ritten_id,$params);            
                redirect('ritten/index');
            }
            else
            {
				$this->load->model('Klanten_model');
				$data['all_klanten'] = $this->Klanten_model->get_all_klanten();

				$this->load->model('Autos_model');
                $data['all_autos'] = $this->Autos_model->get_all_autos();
                
                $data['instellingen'] = $this->Ritten_model->get_tarieven();

                $data['_view'] = 'ritten/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('De rit die u probeert te bewerken bestaat niet.');
    } 

    /*
     * Deleting ritten
     */
    function remove($ritten_id)
    {
        $ritten = $this->Ritten_model->get_ritten($ritten_id);

        // check if the ritten exists before trying to delete it
        if(isset($ritten['ritten_id']))
        {
            $this->Ritten_model->delete_ritten($ritten_id);
            redirect('ritten/index');
        }
        else
            show_error('De rit die u probeert te verwijderen bestaat niet.');
    }

}
