<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_chauffeur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_chauffeur_model');
    } 

    /*
     * Listing of status_chauffeur
     */
    function index()
    {
        $data['status_chauffeur'] = $this->Status_chauffeur_model->get_all_status_chauffeur();
        
        $data['_view'] = 'status_chauffeur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new status_chauffeur
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => $this->input->post('status'),
            );
            
            $status_chauffeur_id = $this->Status_chauffeur_model->add_status_chauffeur($params);
            redirect('status_chauffeur/index');
        }
        else
        {            
            $data['_view'] = 'status_chauffeur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a status_chauffeur
     */
    function edit($status_chauffeur_id)
    {   
        // check if the status_chauffeur exists before trying to edit it
        $data['status_chauffeur'] = $this->Status_chauffeur_model->get_status_chauffeur($status_chauffeur_id);
        
        if(isset($data['status_chauffeur']['status_chauffeur_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
                );

                $this->Status_chauffeur_model->update_status_chauffeur($status_chauffeur_id,$params);            
                redirect('status_chauffeur/index');
            }
            else
            {
                $data['_view'] = 'status_chauffeur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The status_chauffeur you are trying to edit does not exist.');
    } 

    /*
     * Deleting status_chauffeur
     */
    function remove($status_chauffeur_id)
    {
        $status_chauffeur = $this->Status_chauffeur_model->get_status_chauffeur($status_chauffeur_id);

        // check if the status_chauffeur exists before trying to delete it
        if(isset($status_chauffeur['status_chauffeur_id']))
        {
            $this->Status_chauffeur_model->delete_status_chauffeur($status_chauffeur_id);
            redirect('status_chauffeur/index');
        }
        else
            show_error('The status_chauffeur you are trying to delete does not exist.');
    }
    
}
