<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_auto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_auto_model');
    } 

    /*
     * Listing of status_auto
     */
    function index()
    {
        $data['status_auto'] = $this->Status_auto_model->get_all_status_auto();
        
        $data['_view'] = 'status_auto/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new status_auto
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => $this->input->post('status'),
            );
            
            $status_auto_id = $this->Status_auto_model->add_status_auto($params);
            redirect('status_auto/index');
        }
        else
        {            
            $data['_view'] = 'status_auto/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a status_auto
     */
    function edit($status_auto_id)
    {   
        // check if the status_auto exists before trying to edit it
        $data['status_auto'] = $this->Status_auto_model->get_status_auto($status_auto_id);
        
        if(isset($data['status_auto']['status_auto_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
                );

                $this->Status_auto_model->update_status_auto($status_auto_id,$params);            
                redirect('status_auto/index');
            }
            else
            {
                $data['_view'] = 'status_auto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The status_auto you are trying to edit does not exist.');
    } 

    /*
     * Deleting status_auto
     */
    function remove($status_auto_id)
    {
        $status_auto = $this->Status_auto_model->get_status_auto($status_auto_id);

        // check if the status_auto exists before trying to delete it
        if(isset($status_auto['status_auto_id']))
        {
            $this->Status_auto_model->delete_status_auto($status_auto_id);
            redirect('status_auto/index');
        }
        else
            show_error('The status_auto you are trying to delete does not exist.');
    }
    
}
