<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Klanten_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get klanten by klant_id
     */
    function get_klanten($klant_id)
    {
        return $this->db->get_where('klanten',array('klant_id'=>$klant_id))->row_array();
    }
        
    /*
     * Get all klanten
     */
    function get_all_klanten()
    {
        $this->db->order_by('klant_id', 'desc');
        return $this->db->get('klanten')->result_array();
    }
        
    /*
     * function to add new klanten
     */
    function add_klanten($params)
    {
        $this->db->insert('klanten',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update klanten
     */
    function update_klanten($klant_id,$params)
    {
        $this->db->where('klant_id',$klant_id);
        return $this->db->update('klanten',$params);
    }
    
    /*
     * function to delete klanten
     */
    function delete_klanten($klant_id)
    {
        return $this->db->delete('klanten',array('klant_id'=>$klant_id));
    }
}
