<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ritten_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ritten by ritten_id
     */
    function get_ritten($ritten_id)
    {
        return $this->db->get_where('ritten',array('ritten_id'=>$ritten_id))->row_array();
    }
        
    /*
     * Get all ritten
     */
    function get_all_ritten($limit = FALSE, $offset = FALSE)
    {
        if($limit)
        {
            $this->db->limit($limit, $offset);
        }
        $this->db->order_by('datum desc, vertrektijd');
        $this->db->join('autos', 'autos.auto_id = ritten.auto_id');
        $this->db->join('klanten', 'klanten.klant_id = ritten.klant_id');
        return $this->db->get('ritten')->result_array();
    }
        
    /*
     * function to add new ritten
     */
    function add_ritten($params)
    {
        $this->db->insert('ritten',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ritten
     */
    function update_ritten($ritten_id,$params)
    {
        $this->db->where('ritten_id',$ritten_id);
        return $this->db->update('ritten',$params);
    }
    
    /*
     * function to delete ritten
     */
    function delete_ritten($ritten_id)
    {
        return $this->db->delete('ritten',array('ritten_id'=>$ritten_id));
    }

    /*
     * Haal tarieven op
     */

    public function get_tarieven()
    {
        return $this->db->get_where('instellingen', array('instellingen_id' => 1))->row_array();
    }
}
