<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_auto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get status_auto by status_auto_id
     */
    function get_status_auto($status_auto_id)
    {
        return $this->db->get_where('status_auto',array('status_auto_id'=>$status_auto_id))->row_array();
    }
        
    /*
     * Get all status_auto
     */
    function get_all_status_auto()
    {
        $this->db->order_by('status_auto_id', 'desc');
        return $this->db->get('status_auto')->result_array();
    }
        
    /*
     * function to add new status_auto
     */
    function add_status_auto($params)
    {
        $this->db->insert('status_auto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update status_auto
     */
    function update_status_auto($status_auto_id,$params)
    {
        $this->db->where('status_auto_id',$status_auto_id);
        return $this->db->update('status_auto',$params);
    }
    
    /*
     * function to delete status_auto
     */
    function delete_status_auto($status_auto_id)
    {
        return $this->db->delete('status_auto',array('status_auto_id'=>$status_auto_id));
    }
}
